window.MENUS = [{
    text: '基本用法',
    icon: './res/icon/house.png',
    children: [{
        text: '你好 FineUI',
        href: './basic/hello.html'
    }, {
        text: '登陆页面',
        href: './basic/login.html'
    }, {
        text: '登陆页面（回车导航）',
        href: './basic/login_enterkey.html'
    }]
}, {
    text: '表单控件',
    icon: './res/icon/application_form.png',
    children: [{
        text: '按钮控件',
        children: [{
            text: '简单按钮',
            href: './button/button.html'
        }, {
            text: '按钮图标',
            href: './button/button_icon.html'
        }, {
            text: '按钮图标（图标字体）',
            href: './button/button_iconfont.html'
        }, {
            text: '链接按钮',
            href: './button/button_linkbutton.html'
        }, {
            text: '菜单按钮',
            href: './button/button_menu.html'
        }, {
            text: '自定义按钮',
            href: './button/button_custom.html'
        }, {
            text: '按钮的宽度高度',
            href: './button/button_widthheight.html'
        }, {
            text: '按钮分组',
            children: [{
                text: '按钮分组',
                href: './button/button_buttongroup.html'
            }, {
                text: '按钮分组（垂直显示）',
                href: './button/button_buttongroup_vertical.html'
            }, {
                text: '按钮分组（按下状态分组）',
                href: './button/button_buttongroup_pressgroup.html'
            }]
        }]
    }, {
        text: '基本元素',
        children: [{
            text: '文本标签',
            href: './form/label.html'
        }, {
            text: '超链接',
            href: './form/hyperlink.html'
        }, {
            text: '图片控件',
            href: './form/image.html'
        }, {
            text: '图片控件（注册点击事件）',
            href: './form/image_click.html'
        }, {
            text: '提示信息',
            href: './form/tooltip.html'
        }, {
            text: '日期控件',
            href: './form/calendar.html'
        }, {
            text: '日期控件（最小日期和最大日期）',
            href: './form/calendar_mindate.html'
        }, {
            text: '日期控件（选择时间）',
            href: './form/calendar_time.html'
        }, {
            text: '日期控件（选择时间，不显示秒钟）',
            href: './form/calendar_time_showsecond.html'
        }]
    }, {
        text: '输入框',
        children: [{
            text: '文本框',
            href: './form/textbox.html'
        }, {
            text: '文本框（改变事件）',
            href: './form/textbox_changevent.html'
        }, {
            text: '自动扩展高度',
            href: './form/textarea_autogrow.html'
        }, {
            text: '富文本编辑器',
            href: './form/htmleditor.html'
        }, {
            text: '触发器输入框',
            href: './form/triggerbox.html'
        }, {
            text: '两个触发器输入框',
            href: './form/twintriggerbox.html'
        }, {
            text: '两个触发器输入框（失去焦点事件）',
            href: './form/twintriggerbox_blur.html'
        }, {
            text: '数字输入框',
            href: './form/numberbox.html'
        }, {
            text: '数字输入框（改变事件）',
            href: './form/numberbox_textchange.html'
        }, {
            text: '数字输入框（精度）',
            href: './form/numberbox_decimalprecision.html'
        }, {
            text: '数字输入框（千分位）',
            href: './form/numberbox_commas.html'
        }, {
            text: '数字输入框（四舍五入）',
            href: './form/numberbox_round.html'
        }, {
            text: '数字输入框（去除小数后面的零）',
            href: './form/numberbox_trimend.html'
        }, {
            text: '日期选择框',
            href: './form/datepicker.html'
        }, {
            text: '日期选择框（选中事件）',
            href: './form/datepicker_selectevent.html'
        }, {
            text: '日期选择框（限制范围）',
            href: './form/datepicker_range.html'
        }, {
            text: '日期选择框（选择时间）',
            href: './form/datepicker_time.html'
        }, {
            text: '日期选择框（选择时间，不显示秒钟）',
            href: './form/datepicker_time_showsecond.html'
        }, {
            text: '时间选择框',
            href: './form/timepicker.html'
        }, {
            text: '时间选择框（清空图标）',
            href: './form/timepicker_clearicon.html'
        }]
    }, {
        text: '选择框',
        children: [{
            text: '复选框',
            href: './form/checkbox.html'
        }, {
            text: '复选框列表',
            href: './form/checkboxlist.html'
        }, {
            text: '更新复选框列表',
            href: './form/checkboxlist_update.html'
        }, {
            text: '复选框列表（自适应列宽度）',
            href: './form/checkboxlist_autocolumnwidth.html'
        }, {
            text: '复选框列表（最多选中一项）',
            href: './form/checkboxlist_radio.html'
        }, {
            text: '复选框列表（至少选中一项）',
            href: './form/checkboxlist_at_least_one.html'
        }, {
            text: '单选框',
            href: './form/radiobutton.html'
        }, {
            text: '单选框列表',
            href: './form/radiobuttonlist.html'
        }, {
            text: '更新单选框列表',
            href: './form/radiobuttonlist_update.html'
        }, {
            text: '单选框列表（自适应列宽度）',
            href: './form/radiobuttonlist_autocolumnwidth.html'
        }]
    }, {
        text: '表单验证',
        children: [{
            text: '表单验证',
            href: './form/form_validate.html'
        }, {
            text: '表单验证（自定义验证函数）',
            href: './form/form_validate_validator.html'
        }, {
            text: '表单验证（自定义验证函数，参数）',
            href: './form/form_validate_validator_params.html'
        }, {
            text: '表单验证（标记为无效）',
            href: './form/form_validate_markinvalid.html'
        }, {
            text: '验证多个表单',
            href: './form/form_validate_multi.html'
        }]
    }, {
        text: '上传控件',
        children: [{
            text: '上传控件',
            href: './form/fileupload.html'
        }, {
            text: '上传控件（改变事件）',
            href: './form/fileupload_change.html'
        }, {
            text: '工具栏中的上传控件',
            href: './form/fileupload_toolbar.html'
        }]
    }, {
        text: '表单布局',
        children: [{
            text: '按钮与表单',
            href: './form/layout_buttons.html'
        }, {
            text: '复杂布局（列布局）',
            href: './form/layout_panel_column.html'
        }, {
            text: '复杂布局（联系我们）',
            href: './form/layout_contactus.html'
        }, {
            text: '复杂布局（账单信息）',
            href: './form/layout_checkout.html'
        }, {
            text: '按钮水平居中',
            href: './form/layout_center_button.html'
        }, {
            text: '表单中的多行按钮',
            href: './form/layout_multiline_buttons.html'
        }]
    }, {
        text: '下拉列表控件',
        children: [{
            text: '下拉列表',
            href: './dropdownlist/dropdownlist.html'
        }, {
            text: '下拉列表（可编辑，强制选择）',
            href: './dropdownlist/dropdownlist_editable.html'
        }, {
            text: '下拉列表（可编辑，不强制选择）',
            href: './dropdownlist/dropdownlist_no_forceselection.html'
        }, {
            text: '多选',
            children: [{
                text: '下拉列表（多选）',
                href: './dropdownlist/multiselect.html'
            }, {
                text: '下拉列表（多选，清空图标）',
                href: './dropdownlist/multiselect_clearicon.html'
            }, {
                text: '下拉列表（多选，清空图标事件）',
                href: './dropdownlist/multiselect_cleariconclick.html'
            }, {
                text: '下拉列表（多选复选框）',
                href: './dropdownlist/multiselect_checkboxselect.html'
            }, {
                text: '下拉列表（多选，可编辑，强制选择）',
                href: './dropdownlist/multiselect_editable.html'
            }, {
                text: '下拉列表（多选，可编辑，不强制选择）',
                href: './dropdownlist/multiselect_editable_no_forceselection.html'
            }]
        }, {
            text: '自定义列表项',
            children: [{
                text: '列表项图标',
                href: './dropdownlist/dropdownlist_itemicon.html'
            }, {
                text: '自定义列表项',
                href: './dropdownlist/dropdownlist_displayfield.html'
            }, {
                text: '列表项分组',
                href: './dropdownlist/dropdownlist_group.html'
            }, {
                text: '自定义列表项（分组）',
                href: './dropdownlist/dropdownlist_displayfield_group.html'
            }, {
                text: '自定义列表项（分组，多选，复选框）',
                href: './dropdownlist/dropdownlist_displayfield_group_multiselect.html'
            }]
        }, {
            text: '杂项',
            children: [{
                text: '模拟树的下拉列表',
                href: './dropdownlist/dropdownlist_simulate_tree.html'
            }, {
                text: '中国省市县联动',
                href: './dropdownlist/shengshixian.html'
            }, {
                text: '下拉列表（matchFieldWidth）',
                href: './dropdownlist/dropdownlist_matchfieldwidth.html'
            }, {
                text: '下拉列表（禁止选择项）',
                href: './dropdownlist/dropdownlist_itemdisable.html'
            }, {
                text: '下拉列表（初始值为空）',
                href: './dropdownlist/dropdownlist_emptytext.html'
            }, {
                text: '下拉列表（可编辑，不强制选择，自定义初始值）',
                href: './dropdownlist/dropdownlist_no_forceselection_initvalue.html'
            }, {
                text: '下拉列表（多选，改变事件）',
                href: './dropdownlist/multiselect_change.html'
            }]
        }]
    }, {
        text: '下拉框控件',
        children: [{
            text: '下拉单选框列表',
            children: [{
                text: '下拉单选框列表',
                href: './dropdownbox/dropdownbox_radiobuttonlist.html'
            }, {
                text: '下拉单选框列表（滚动条）',
                href: './dropdownbox/dropdownbox_radiobuttonlist_autoscroll.html'
            }, {
                text: '下拉单选框列表（MatchFieldWidth）',
                href: './dropdownbox/dropdownbox_radiobuttonlist_matchfieldwidth.html'
            }, {
                text: '下拉单选框列表（MatchFieldWidth，右侧空间不足）',
                href: './dropdownbox/dropdownbox_radiobuttonlist_matchfieldwidth_right.html'
            }],
        }, {
            text: '下拉复选框列表',
            children: [{
                text: '下拉复选框列表',
                href: './dropdownbox/dropdownbox_checkboxlist.html'
            }, {
                text: '下拉复选框列表（全选）',
                href: './dropdownbox/dropdownbox_checkboxlist_selectall.html'
            }],
        }, {
            text: '下拉树',
            children: [{
                text: '下拉树',
                href: './dropdownbox/dropdownbox_tree.html'
            }, {
                text: '下拉树（多选）',
                href: './dropdownbox/dropdownbox_tree_multiselect.html'
            }, {
                text: '下拉树（多选，延迟加载）',
                href: './dropdownbox/dropdownbox_tree_multiselect_lazyload.html'
            }, {
                text: '下拉树（多选，延迟加载，初始值）',
                href: './dropdownbox/dropdownbox_tree_multiselect_lazyload_defaultvalue.html'
            }],
        }, {
            text: '下拉表格',
            children: [{
                text: '下拉表格（单选，初始值）',
                href: './dropdownbox/dropdownbox_grid.html'
            }, {
                text: '下拉表格（单选，改变事件）',
                href: './dropdownbox/dropdownbox_grid_change.html'
            }, {
                text: '下拉表格（单选，更新选中值）',
                href: './dropdownbox/dropdownbox_grid_updatevalue.html'
            }, {
                text: '下拉表格（多选，初始值）',
                href: './dropdownbox/dropdownbox_grid_multiselect.html'
            }, {
                text: '下拉表格（多选，改变事件）',
                href: './dropdownbox/dropdownbox_grid_multiselect_change.html'
            }, {
                text: '下拉表格（多选，更新选中值）',
                href: './dropdownbox/dropdownbox_grid_multiselect_updatevalue.html'
            }, {
                text: '下拉表格（内存分页）',
                href: './dropdownbox/dropdownbox_grid_paging.html'
            }, {
                text: '下拉表格（数据库分页）',
                href: './dropdownbox/dropdownbox_grid_paging_database.html'
            }, {
                text: '下拉表格（数据库分页，初始值）',
                href: './dropdownbox/dropdownbox_grid_paging_database_defaultvalue.html'
            }, {
                text: '下拉表格（数据库分页，更新选中值）',
                href: './dropdownbox/dropdownbox_grid_paging_database_updatevalue.html'
            }, {
                text: '下拉表格（数据库分页，清空图标）',
                href: './dropdownbox/dropdownbox_grid_paging_database_clearicon.html'
            }, {
                text: '下拉表格（输入框过滤）',
                href: './dropdownbox/dropdownbox_grid_search.html'
            }, {
                text: '下拉表格（复杂布局）',
                href: './dropdownbox/dropdownbox_grid_layout.html'
            }, {
                text: '下拉表格（复杂布局，单选）',
                href: './dropdownbox/dropdownbox_grid_layout_singleselect.html'
            }, {
                text: '下拉表格（客户端全选）',
                href: './dropdownbox/dropdownbox_grid_selectall.html'
            }],
        }, {
            text: '自定义下拉框',
            children: [{
                text: '自定义下拉框',
                href: './dropdownbox/dropdownbox_themes.html'
            }],
        }, {
            text: '杂项',
            children: [{
                text: '总是显示弹出面板',
                href: './dropdownbox/dropdownbox_grid_layout_alwaysdisplay.html'
            }, {
                text: '总是显示弹出面板（初始值）',
                href: './dropdownbox/dropdownbox_grid_layout_alwaysdisplay_defaultvalue.html'
            }, {
                text: '总是显示弹出面板（隐藏输入框）',
                href: './dropdownbox/dropdownbox_grid_layout_alwaysdisplay_hidden.html'
            }, {
                text: '下拉单选框列表（用户自行输入值）',
                href: './dropdownbox/dropdownbox_radiobuttonlist_enableedit.html'
            }, {
                text: '下拉复选框列表（用户自行输入值）',
                href: './dropdownbox/dropdownbox_checkboxlist_enableedit.html'
            }, {
                text: '下拉表格（单选，用户自行输入值）',
                href: './dropdownbox/dropdownbox_grid_enableedit.html'
            }, {
                text: '下拉表格（多选，用户自行输入值）',
                href: './dropdownbox/dropdownbox_grid_multiselect_enableedit.html'
            }]
        }]
    }, {
        text: '表格样式',
        children: [{
            text: '表格样式（简单表单）',
            href: './formtable/tablestyle_simpleform.html'
        }, {
            text: '表格样式（表单）',
            href: './formtable/tablestyle_form.html'
        }, {
            text: '表格样式（复选框列表）',
            href: './formtable/tablestyle_checkboxlist.html'
        }, {
            text: '表格样式（上传控件）',
            href: './formtable/tablestyle_fileupload.html'
        }, {
            text: '表格样式（表单验证）',
            href: './formtable/tablestyle_form_validate.html'
        }, {
            text: '表格样式（联系我们）',
            href: './formtable/tablestyle_layout_contactus.html'
        }, {
            text: '表格样式（联系我们，不显示边框）',
            href: './formtable/tablestyle_layout_contactus_border.html'
        }]
    }, {
        text: '杂项',
        children: [{
            text: '重置表单',
            href: './form/form_reset.html'
        }, {
            text: '隐藏表单字段',
            href: './form/form_hide_field.html'
        }, {
            text: '禁用与只读',
            href: './form/form_disabled.html'
        }, {
            text: '更新标签和必填项',
            href: './form/form_update_label.html'
        }, {
            text: '红色星号的显示位置',
            href: './form/form_redstarposition.html'
        }, {
            text: '自定义标签宽度和位置',
            href: './form/form_labelwidth.html'
        }, {
            text: '标签换行',
            href: './form/form_longlabel.html'
        }, {
            text: '表单字段前缀和后缀',
            href: './form/form_prefix_suffix.html'
        }, {
            text: '列布局（混合使用百分比和固定宽度）',
            href: './form/form_columnwidths.html'
        }, {
            text: 'attrs属性',
            href: './form/form_attrs.html'
        }, {
            text: '输入框文本居中',
            href: './form/form_textalign.html'
        }, {
            text: '自定义触发器输入框图标',
            href: './form/triggerbox_triggerboxurl.html'
        }]
    }]
}, {
    text: '表格控件',
    icon: './res/icon/application_view_columns.png',
    children: [{
        text: '基本用法',
        children: [{
            text: '表格（网址数据）',
            href: './grid/grid.html'
        }, {
            text: '表格（内联数据）',
            href: './grid/grid_inlinedata.html'
        }]
    }, {
        text: '分页与排序',
        children: [{
            text: '排序',
            href: './grid/grid_sorting.html'
        }, {
            text: '内存分页',
            href: './grid/grid_paging.html'
        }, {
            text: '数据库分页',
            href: './grid/grid_paging_database.html'
        }, {
            text: '内存分页与排序',
            href: './grid/grid_paging_sorting.html'
        }, {
            text: '数据库分页与排序',
            href: './grid/grid_paging_database_sorting.html'
        }, {
            text: '自定义内存分页',
            href: './grid/grid_custom_paging.html'
        }, {
            text: '自定义数据库分页',
            href: './grid/grid_custom_paging_database.html'
        }, {
            text: '数据库分页（底部工具栏）',
            href: './grid/grid_paging_database_bbar.html'
        }, {
            text: '分页类型',
            href: './grid/grid_pagingtype.html'
        }]
    }, {
        text: '序号列',
        children: [{
            text: '序号列（内存分页）',
            href: './grid/grid_rownumber_paging.html'
        }, {
            text: '序号列（数据库分页）',
            href: './grid/grid_rownumber_paging_database.html'
        }, {
            text: '序号列（自定义宽度）',
            href: './grid/grid_rownumber_width.html'
        }, {
            text: '序号列（靠左显示）',
            href: './grid/grid_rownumber_align.html'
        }]
    }, {
        text: '行选择',
        children: [{
            text: '行选择（多选）',
            href: './grid/grid_checkall.html'
        }, {
            text: '行选择（单选）',
            href: './grid/grid_checkall_singleselect.html'
        }, {
            text: '行选择（只能通过全选框选中行）',
            href: './grid/grid_checkall_only.html'
        }, {
            text: '行选择（保持选中行）',
            href: './grid/grid_checkall_keepcurrentselection.html'
        }, {
            text: '行选择（禁止选择某些行）',
            href: './grid/grid_checkall_rowselectable.html'
        }, {
            text: '行选择（禁止选择某些行，整行变灰）',
            href: './grid/grid_checkall_rowselectable_disabled.html'
        }]
    }, {
        text: '扩展列',
        children: [{
            text: '行扩展列',
            href: './grid/grid_rowexpander.html'
        }, {
            text: '行扩展列（展开全部）',
            href: './grid/grid_rowexpander_expandall.html'
        }, {
            text: '弹出窗体列',
            href: './grid/grid_iframe.html'
        }, {
            text: '弹出窗体列（窗体初始最大化）',
            href: './grid/grid_iframe_maximized.html'
        }, {
            text: '弹出窗体列（选中多行）',
            href: './grid/grid_iframe_multi.html'
        }]
    }, {
        text: '事件',
        children: [{
            text: '行内按钮事件',
            href: './grid/grid_rowcommand.html'
        }, {
            text: '行内按钮事件（字体图标）',
            href: './grid/grid_rowcommand_iconfont.html'
        }, {
            text: '行内按钮事件（内存分页）',
            href: './grid/grid_rowcommand_paging.html'
        }, {
            text: '行内按钮事件（数据库分页）',
            href: './grid/grid_rowcommand_paging_database.html'
        }, {
            text: '行单击事件',
            href: './grid/grid_rowcommand_rowclick.html'
        }, {
            text: '行双击事件',
            href: './grid/grid_rowcommand_rowdblclick.html'
        }, {
            text: '行选中事件',
            href: './grid/grid_rowcommand_rowselect.html'
        }]
    }, {
        text: '复选框列',
        children: [{
            text: '复选框列',
            href: './grid/grid_checkboxfield.html'
        }, {
            text: '复选框列（改变事件）',
            href: './grid/grid_checkboxfield_changeevent.html'
        }, {
            text: '复选框列（全选与反选）',
            href: './grid/grid_checkboxfield_checkall.html'
        }]
    }, {
        text: '分页工具栏',
        children: [{
            text: '重新绑定数据',
            href: './grid/grid_pageitems.html'
        }, {
            text: '展开折叠行扩展列',
            href: './grid/grid_pageitems_rowexpander.html'
        }, {
            text: '改变每页记录数（内存分页）',
            href: './grid/grid_pageitems_pagesize.html'
        }, {
            text: '改变每页记录数（数据库分页）',
            href: './grid/grid_pageitems_pagesize_database.html'
        }]
    }, {
        text: '列宽度',
        children: [{
            text: '各列宽度固定',
            href: './grid/grid_width.html'
        }, {
            text: '自适应列（一列）',
            href: './grid/grid_width_flex.html'
        }, {
            text: '自适应列（多列）',
            href: './grid/grid_width_multi_flex.html'
        }, {
            text: '各列宽度自适应',
            href: './grid/grid_width_forcefit.html'
        }, {
            text: '各列宽度自适应（最小列宽度）',
            href: './grid/grid_width_forcefit_minwidth.html'
        }]
    }, {
        text: '标题栏',
        children: [{
            text: '隐藏标题栏',
            href: './grid/grid_header_hide.html'
        }, {
            text: '改变标题栏文本和宽度',
            href: './grid/grid_header_changetextwidth.html'
        }, {
            text: '标题栏自动换行',
            href: './grid/grid_header_wrap.html'
        }, {
            text: '禁用表头菜单和列宽度调整',
            href: './grid/grid_header_disablemenu.html'
        }]
    }, {
        text: '多表头',
        children: [{
            text: '多表头',
            href: './grid/grid_groupheader.html'
        }, {
            text: '多表头（排序）',
            href: './grid/grid_groupheader_sort.html'
        }, {
            text: '多表头（初始隐藏列）',
            href: './grid/grid_groupheader_hidden.html'
        }]
    }, {
        text: '合计行',
        children: [{
            text: '合计行',
            href: './grid/grid_summary.html'
        }, {
            text: '合计行（当前页合计）',
            href: './grid/grid_summary_currentpage.html'
        }, {
            text: '合计行（横向纵向滚动条）',
            href: './grid/grid_summary_scrollbar_flow.html'
        }, {
            text: '合计行（浮动到底部，横向纵向滚动条）',
            href: './grid/grid_summary_scrollbar_bottom.html'
        }, {
            text: '合计行（浮动到顶部，横向纵向滚动条，当前页合计）',
            href: './grid/grid_summary_scrollbar_top.html'
        }]
    }, {
        text: '单元格编辑',
        children: [{
            text: '单元格编辑',
            href: './grideditor/grideditor.html'
        }, {
            text: '单元格渲染函数（renderer）',
            href: './grideditor/grideditor_renderer.html'
        }, {
            text: '键盘操作',
            children: [{
                text: '单元格编辑（Tab纵向导航）',
                href: './grideditor/grideditor_vertical_tab.html'
            }, {
                text: '单元格编辑（Enter键和Tab键行为相同）',
                href: './grideditor/grideditor_entersameastab.html'
            }, {
                text: '单元格编辑（Enter纵向导航，并选中输入框内文本）',
                href: './grideditor/grideditor_vertical_enter.html'
            }, {
                text: '单元格编辑（Enter纵向导航，自动滚动）',
                href: './grideditor/grideditor_vertical_enter_scrollbar.html'
            }, {
                text: '单元格编辑（Enter纵向导航，最后自动点击保存按钮）',
                href: './grideditor/grideditor_vertical_enter_tosave.html'
            }]
        }, {
            text: '新增删除',
            children: [{
                text: '新增行',
                href: './grideditor/grideditor_new.html'
            }, {
                text: '新增行（定位到某一列）',
                href: './grideditor/grideditor_new_editcolumnid.html'
            }, {
                text: '新增行与删除行',
                href: './grideditor/grideditor_new_delete.html'
            }]
        }, {
            text: '结束编辑',
            children: [{
                text: '结束编辑',
                href: './grideditor/grideditor_afteredit.html'
            }, {
                text: '结束编辑（姓名不能为空）',
                href: './grideditor/grideditor_client_validate.html'
            }, {
                text: '结束编辑（高亮单元格）',
                href: './grideditor/grideditor_renderfunction_complex.html'
            }, {
                text: '结束编辑（更新单元格的值）',
                href: './grideditor/grideditor_updatecellvalue.html'
            }, {
                text: '结束编辑（更新合计行的值）',
                href: './grideditor/grideditor_updatesummary.html'
            }]
        }, {
            text: '数据改变',
            children: [{
                text: '数据改变（启用禁用保存按钮）',
                href: './grideditor/grideditor_datachange.html'
            }, {
                text: '数据改变（关闭页面前提示框）',
                href: './grideditor/grideditor_beforeunload.html'
            }]
        }, {
            text: '禁止编辑',
            children: [{
                text: '禁止列编辑',
                href: './grideditor/grideditor_editable.html'
            }, {
                text: '禁止行编辑',
                href: './grideditor/grideditor_cancelcelledit.html'
            }, {
                text: '禁止单元格编辑',
                href: './grideditor/grideditor_cancelcelledit_somecell.html'
            }]
        }]
    }, {
        text: '列锁定',
        children: [{
            text: '列锁定',
            href: './grid/grid_lockcolumn.html'
        }, {
            text: '列锁定（行扩展列）',
            href: './grid/grid_lockcolumn_rowexpander.html'
        }, {
            text: '列锁定（多表头）',
            href: './grid/grid_lockcolumn_groupheader.html'
        }, {
            text: '列锁定（多表头，行扩展列）',
            href: './grid/grid_lockcolumn_groupheader_rowexpander.html'
        }, {
            text: '列锁定（合计行）',
            href: './grid/grid_lockcolumn_summary.html'
        }, {
            text: '列锁定（合计行，多表头，行扩展列，数据库分页）',
            href: './grid/grid_lockcolumn_summary_groupfield.html'
        }, {
            text: '列锁定（单元格编辑）',
            href: './grid/grid_lockcolumn_editor_cell_new.html'
        }, {
            text: '列锁定（自动换行）',
            href: './grid/grid_lockcolumn_line_wrap.html'
        }]
    }, {
        text: '行与列样式',
        children: [{
            text: '行样式',
            href: './grid/grid_style_row.html'
        }, {
            text: '行样式（rowDataBound）',
            href: './grid/grid_style_rowdatabound.html'
        }, {
            text: '单元格样式',
            href: './grid/grid_style_cell.html'
        }, {
            text: '列样式',
            href: './grid/grid_style_column.html'
        }]
    }, {
        text: '表头过滤',
        children: [{
            text: '过滤',
            href: './grid/grid_filter.html'
        }, {
            text: '过滤（操作符）',
            href: './grid/grid_filter_operator.html'
        }, {
            text: '过滤（多条件）',
            href: './grid/grid_filter_multi.html'
        }, {
            text: '过滤（多条件匹配符）',
            href: './grid/grid_filter_multi_matcher.html'
        }, {
            text: '过滤（数字与日期）',
            href: './grid/grid_filter_number.html'
        }, {
            text: '过滤（复选框列表）',
            href: './grid/grid_filter_checkboxlist.html'
        }, {
            text: '过滤（带图标的下拉列表，多选）',
            href: './grid/grid_filter_dropdownlist.html'
        }]
    }, {
        text: '单元格合并',
        children: [{
            text: '单元格合并',
            href: './grid/grid_mergecells.html'
        }, {
            text: '合并列',
            href: './grid/grid_mergecolumns.html'
        }, {
            text: '合并列（依赖于前一列的合并状态）',
            href: './grid/grid_mergecolumns_depends.html'
        }, {
            text: '合并列（依赖于第一列的合并状态）',
            href: './grid/grid_mergecolumns_dependsfirst.html'
        }, {
            text: '合并列（全部列）',
            href: './grid/grid_mergecolumns_all.html'
        }]
    }, {
        text: '树表格',
        children: [{
            text: '树表格',
            href: './gridtree/gridtree.html'
        }, {
            text: '树表格（树序号）',
            href: './gridtree/gridtree_treenumber.html'
        }, {
            text: '树表格（展开指定行）',
            href: './gridtree/gridtree_expandrows.html'
        }, {
            text: '树表格（展开全部行）',
            href: './gridtree/gridtree_expandallrows.html'
        }, {
            text: '树表格（隐藏节点图标）',
            href: './gridtree/gridtree_noicons.html'
        }, {
            text: '树表格（节点图标）',
            href: './gridtree/gridtree_icons.html'
        }, {
            text: '树表格（右键菜单）',
            href: './gridtree/gridtree_contextmenu.html'
        }, {
            text: '树表格（内存分页）',
            href: './gridtree/gridtree_paging.html'
        }, {
            text: '树表格（数据库分页）',
            href: './gridtree/gridtree_paging_database.html'
        }, {
            text: '树表格（合计行，数据库分页）',
            href: './gridtree/gridtree_paging_database_summarydata.html'
        }, {
            text: '树表格（锁定列，合计行，数据库分页）',
            href: './gridtree/gridtree_paging_database_summarydata_lockcolumn.html'
        }]
    }, {
        text: '行与列移动',
        children: [{
            text: '列移动',
            href: './grid/grid_columnmove.html'
        }, {
            text: '列移动（列锁定）',
            href: './grid/grid_columnmove_lockcolumn.html'
        }, {
            text: '列移动（多表头）',
            href: './grid/grid_columnmove_groupfield.html'
        }, {
            text: '列移动（保存列顺序+宽度+隐藏）',
            href: './grid/grid_columnmove_orderwidthhidden.html'
        }, {
            text: '行移动（上下移动）',
            href: './grid/grid_rowmove.html'
        }, {
            text: '行移动（上下移动，多选）',
            href: './grid/grid_rowmove_multi.html'
        }, {
            text: '行移动（双选框）',
            href: './grid/grid_rowmove_between2grid.html'
        }, {
            text: '表格列配置',
            href: './grid/grid_rowmove_columnconfig.html'
        }]
    }, {
        text: '大数据表格',
        children: [{
            text: '大数据（1,000）',
            href: './grid/grid_bigdata_1000.html'
        }, {
            text: '大数据（5,000）',
            href: './grid/grid_bigdata_5000.html'
        }, {
            text: '大数据（10,000）',
            href: './grid/grid_bigdata_10000.html'
        }, {
            text: '大数据（10,000，行定位）',
            href: './grid/grid_bigdata_10000_location.html'
        }, {
            text: '大数据（10,000，自定义行数提示）',
            href: './grid/grid_bigdata_10000_rowtip.html'
        }, {
            text: '大数据（10,000，客户端分页）',
            href: './grid/grid_bigdata_10000_paging.html'
        }, {
            text: '大数据（10,000，服务端分页）',
            href: './grid/grid_bigdata_10000_paging_database.html'
        }]
    }, {
        text: '杂项',
        children: [{
            text: '主从表联动',
            href: './grid/grid_other_twogrid.html'
        }, {
            text: '文本居中显示',
            href: './grid/grid_other_centercolumn.html'
        }, {
            text: '显示隐藏列',
            href: './grid/grid_other_hidecolumn.html'
        }, {
            text: '启用文字选择',
            href: './grid/grid_other_textselection.html'
        }, {
            text: '文字垂直靠上显示',
            href: './grid/grid_other_texttop.html'
        }, {
            text: '列分割线',
            href: './grid/grid_other_column_lines.html'
        }, {
            text: '表格为空的提示',
            href: './grid/grid_other_empty_text.html'
        }, {
            text: '表格为空的提示（绝对定位）',
            href: './grid/grid_other_empty_text_fewcolumns.html'
        }, {
            text: '自动换行',
            href: './grid/grid_other_line_wrap.html'
        }, {
            text: '右键菜单(全选复选框列）',
            href: './grid/grid_other_checkboxfield_contextmenu.html'
        }, {
            text: '在新标签页中打开',
            href: './grid/grid_other_newtab.html'
        }, {
            text: '在新标签页中打开（同一个标签页）',
            href: './grid/grid_other_newtab_sametab.html'
        }]
    }]
}, {
    text: '更多控件',
    icon: './res/icon/bricks.png',
    children: [{
        text: '树控件',
        children: [{
            text: '简单树控件',
            href: './tree/tree.html'
        }, {
            text: '延迟加载的树控件',
            href: './tree/tree_lazy.html'
        }, {
            text: '智能树控件',
            href: './tree/tree_smart.html'
        }, {
            text: '节点图标',
            children: [{
                text: '节点图标',
                href: './tree/tree_icon.html'
            }, {
                text: '节点图标字体',
                href: './tree/tree_iconfont.html'
            }, {
                text: '隐藏节点图标',
                href: './tree/tree_icons.html'
            }]
        }, {
            text: '复选框',
            children: [{
                text: '简单复选框',
                href: './tree/tree_checkbox.html'
            }, {
                text: '复选框（全选与反选）',
                href: './tree/tree_checkbox_checkall.html'
            }]
        }, {
            text: '节点选择',
            children: [{
                text: '节点选择（单选）',
                href: './tree/tree_select.html'
            }, {
                text: '节点选择（多选）',
                href: './tree/tree_multiselect.html'
            }, {
                text: '节点选择（保持选中节点）',
                href: './tree/tree_multiselect_keepcurrentselection.html'
            }, {
                text: '节点选择（禁止选中节点）',
                href: './tree/tree_multiselect_selectable.html'
            }, {
                text: '节点选择（禁止选中节点，默认选中）',
                href: './tree/tree_multiselect_selectable_selected.html'
            }]
        }, {
            text: '事件',
            children: [{
                text: '节点点击事件',
                href: './tree/tree_nodeclickevent.html'
            }, {
                text: '节点展开折叠事件',
                href: './tree/tree_nodeexpandevent.html'
            }]
        }, {
            text: '杂项',
            children: [{
                text: '右键菜单（展开全部子节点）',
                href: './tree/tree_contextmenu.html'
            }, {
                text: '节点超链接（点击文字外区域也有效）',
                href: './tree/tree_nodehyperlink.html'
            }, {
                text: '同级节点只能展开一个',
                href: './tree/tree_singleexpand.html'
            }, {
                text: '启用文字选择',
                href: './tree/tree_textselection.html'
            }, {
                text: '节点样式',
                href: './tree/tree_node_cssclass.html'
            }, {
                text: '超链接树节点',
                href: './tree/tree_link.html'
            }, {
                text: '简单树控件（单击展开折叠）',
                href: './tree/tree_singleclickexpand.html'
            }, {
                text: '简单树控件（高度自适应）',
                href: './tree/tree_autoheight.html'
            }]
        }]
    }, {
        text: '选项卡控件',
        children: [{
            text: '选项卡',
            href: './tabstrip/tabstrip.html'
        }, {
            text: '选项卡（改变事件）',
            href: './tabstrip/tabstrip_tabchange.html'
        }, {
            text: '选项卡（右键菜单）',
            href: './tabstrip/tabstrip_menu.html'
        }, {
            text: '选项卡标题栏',
            children: [{
                text: '选项卡的位置',
                href: './tabstrip/tabstrip_position.html'
            }, {
                text: '选项卡的位置（右侧工具图标）',
                href: './tabstrip/tabstrip_position_tools.html'
            }, {
                text: '初始隐藏全部选项卡',
                href: './tabstrip/tabstrip_notabs.html'
            }, {
                text: '选项卡标题为空',
                href: './tabstrip/tabstrip_notitle.html'
            }, {
                text: '隐藏选项卡标题栏',
                href: './tabstrip/tabstrip_noheader.html'
            }, {
                text: '选项卡的对齐方式',
                href: './tabstrip/tabstrip_align.html'
            }, {
                text: '选项卡填充整个标题栏',
                href: './tabstrip/tabstrip_fill.html'
            }, {
                text: '选项卡标题边框',
                href: './tabstrip/tabstrip_bordercolor.html'
            }, {
                text: '选项卡标题背景',
                href: './tabstrip/tabstrip_plain.html'
            }]
        }, {
            text: '杂项',
            children: [{
                text: '自定义右键菜单项',
                href: './tabstrip/tabstrip_closemenu.html'
            }, {
                text: '按钮放在选项卡前面',
                href: './tabstrip/tabstrip_prefixtabs.html'
            }, {
                text: '双击关闭选项卡',
                href: './tabstrip/tabstrip_closeondblclick.html'
            }, {
                text: '选项卡与内联框架',
                href: './tabstrip/tabstrip_iframe.html'
            }, {
                text: '可关闭选项卡',
                href: './tabstrip/tabstrip_closable.html'
            }, {
                text: '选项卡的左右按钮',
                href: './tabstrip/tabstrip_scroll.html'
            }, {
                text: '滚动到特定选项卡',
                href: './tabstrip/tabstrip_scrollto.html'
            }, {
                text: '新增选项卡',
                href: './tabstrip/tabstrip_add.html'
            }]
        }]
    }, {
        text: '手风琴',
        children: [{
            text: '手风琴',
            href: './accordion/accordion.html'
        }, {
            text: '手风琴（窗格改变事件）',
            href: './accordion/accordion_panechange.html'
        }, {
            text: '手风琴（树控件）',
            href: './accordion/accordion_tree.html'
        }, {
            text: '手风琴（自动高度）',
            href: './accordion/accordion_fill.html'
        }, {
            text: '手风琴（工具图标）',
            href: './accordion/accordion_tool.html'
        }]
    }, {
        text: '面板控件',
        children: [{
            text: '面板',
            href: './panel/panel.html'
        }, {
            text: '分组面板',
            href: './panel/grouppanel.html'
        }, {
            text: '工具图标',
            children: [{
                text: '面板（工具图标）',
                href: './panel/panel_tools.html'
            }, {
                text: '面板（自定义工具图标在前面）',
                href: './panel/panel_tools_customtoolahead.html'
            }, {
                text: '面板（工具图标文字）',
                href: './panel/panel_tools_text.html'
            }, {
                text: '面板（自定义折叠图标）',
                href: './panel/panel_tools_custom_expand.html'
            }]
        }, {
            text: '杂项',
            children: [{
                text: '面板（折叠事件）',
                href: './panel/panel_collapse.html'
            }, {
                text: '面板（初始禁用）',
                href: './panel/panel_disabled.html'
            }, {
                text: '面板（背景图片）',
                href: './panel/panel_bgimage.html'
            }]
        }]
    }, {
        text: '窗体控件',
        children: [{
            text: '窗体',
            href: './window/window.html'
        }, {
            text: '最大化',
            children: [{
                text: '窗体（最大化）',
                href: './window/window_maximized.html'
            }, {
                text: '窗体（固定最大化）',
                href: './window/window_maximized_fixed.html'
            }, {
                text: '窗体（最大化时不占据全屏）',
                href: './window/window_maximized_margin.html'
            }]
        }, {
            text: '大小与位置',
            children: [{
                text: '窗体（保持关闭时的位置和大小）',
                href: './window/window_keeplastposition.html'
            }, {
                text: '窗体（限制最小和最大尺寸）',
                href: './window/window_minwidth.html'
            }, {
                text: '窗体（高度自适应页面大小）',
                href: './window/window_height_autosize.html'
            }, {
                text: '窗体（固定在右下角）',
                href: './window/window_bottomright.html'
            }, {
                text: '窗体（百分比宽度和高度）',
                href: './window/window_percent.html'
            }, {
                text: '窗体（显示位置，dependsViewPortSize）',
                href: './window/window_position.html'
            }, {
                text: '窗体（显示位置，fixedPosition）',
                href: './window/window_fixedposition.html'
            }, {
                text: '窗体（侧边窗体）',
                href: './window/window_side.html'
            }]
        }, {
            text: '杂项',
            children: [{
                text: '窗体（工具栏）',
                href: './window/window_toolbar.html'
            }, {
                text: '窗体（表单）',
                href: './window/window_form.html'
            }, {
                text: '窗体（多个窗体）',
                href: './window/window_multi.html'
            }, {
                text: '窗体（图片自适应窗体大小）',
                href: './window/window_image_resize.html'
            }]
        }]
    }, {
        text: '工具栏和菜单',
        children: [{
            text: '内联菜单',
            href: './toolbar/menu.html'
        }, {
            text: '内联菜单（hideOnClick）',
            href: './toolbar/menu_hideonclick.html'
        }, {
            text: '内联菜单（菜单项图标）',
            href: './toolbar/menu_icon.html'
        }, {
            text: '工具栏中的按钮',
            href: './toolbar/menu_button.html'
        }, {
            text: '工具栏与IFrame页面',
            href: './toolbar/toolbar_iframe.html'
        }, {
            text: '单选框与复选框菜单',
            href: './toolbar/menu_checkbox.html'
        }, {
            text: '多行工具栏',
            href: './toolbar/toolbar_multi.html'
        }, {
            text: '工具栏上的表单字段',
            href: './toolbar/formfields.html'
        }, {
            text: '工具栏上的图片（固定宽度）',
            href: './toolbar/toolbar_images_fixedwidth.html'
        }, {
            text: '工具栏上的图片（动态调整）',
            href: './toolbar/toolbar_images.html'
        }, {
            text: '工具栏子项间隔',
            href: './toolbar/toolbar_itemspace.html'
        }, {
            text: '工具栏布局（左中右）',
            href: './toolbar/toolbar_fill.html'
        }, {
            text: '自定义工具栏背景色',
            href: './toolbar/toolbar_custombg.html'
        }, {
            text: '工具栏布局（Fit，HBox）',
            href: './toolbar/toolbar_layout.html'
        }]
    }]
}, {
    text: '移动控件',
    icon: './res/icon/transmit.png',
    children: [{
        text: '移动首页',
        href: './mobile/?file=main.html'
    }, {
        text: '按钮控件',
        children: [{
            text: '按钮',
            href: './mobile/?file=button/button.html'
        }, {
            text: '按钮分组',
            href: './mobile/?file=button/buttongroup.html'
        }, {
            text: '按钮分组（垂直）',
            href: './mobile/?file=button/buttongroup_vertical.html'
        }, {
            text: '按钮分组（与选项卡交互）',
            href: './mobile/?file=button/buttongroup_tabstrip.html'
        }]
    }, {
        text: '面板控件',
        children: [{
            text: '面板',
            href: './mobile/?file=panel/panel.html'
        }, {
            text: '面板（IFrame）',
            href: './mobile/?file=panel/panel_iframe.html'
        }, {
            text: '面板（切换面板）',
            href: './mobile/?file=panel/panel_slide.html'
        }]
    }, {
        text: '手风琴控件',
        children: [{
            text: '手风琴控件',
            href: './mobile/?file=accordion/accordion.html'
        }, {
            text: '手风琴控件（自定义工具图标）',
            href: './mobile/?file=accordion/accordion_tools.html'
        }]
    }, {
        text: '列表控件',
        children: [{
            text: '列表',
            href: './mobile/?file=datalist/datalist.html'
        }, {
            text: '列表（图片与标题）',
            href: './mobile/?file=datalist/datalist_image_title.html'
        }, {
            text: '列表（图片与标题，详细面板，按钮）',
            href: './mobile/?file=datalist/datalist_image_title_button.html'
        }, {
            text: '列表（超链接，新页面中打开）',
            href: './mobile/?file=datalist/datalist_link.html'
        }, {
            text: '列表（超链接，详细面板）',
            href: './mobile/?file=datalist/datalist_linktopanel.html'
        }, {
            text: '列表（超链接，分组）',
            href: './mobile/?file=datalist/datalist_linktopanel_group.html'
        }, {
            text: '列表（超链接，分组，右侧箭头）',
            href: './mobile/?file=datalist/datalist_linktopanel_group_arrow.html'
        }, {
            text: '列表（数据绑定）',
            href: './mobile/?file=datalist/datalist_databind.html'
        }, {
            text: '列表项选择',
            children: [{
                text: '列表项选择（单选）',
                href: './mobile/?file=datalist/datalist_selectedvalue.html'
            }, {
                text: '列表项选择（多选）',
                href: './mobile/?file=datalist/datalist_selectedvaluearray.html'
            }, {
                text: '列表项选择（多选，保持选中项）',
                href: './mobile/?file=datalist/datalist_selectedvaluearray_keepcurrentselection.html'
            }]
        }]
    }, {
        text: '表单控件',
        children: [{
            text: '登录页面',
            href: './mobile/?file=form/login.html'
        }, {
            text: '登录页面（简单错误提示框）',
            href: './mobile/?file=form/login_validatemessageboxplain.html'
        }, {
            text: '登录页面（自定义错误提示框）',
            href: './mobile/?file=form/login_customerrormsg.html'
        }]
    }, {
        text: '窗体控件',
        children: [{
            text: '窗体控件',
            href: './mobile/?file=window/window.html'
        }, {
            text: '窗体控件（f-toolbar-buttonplain）',
            href: './mobile/?file=window/window_buttonplain.html'
        }, {
            text: '窗体控件（点击遮罩层时隐藏）',
            href: './mobile/?file=window/window_hideonmaskclick.html'
        }, {
            text: '侧边窗体',
            children: [{
                text: '侧边窗体',
                href: './mobile/?file=window/window_position.html'
            }, {
                text: '侧边窗体（百分比大小）',
                href: './mobile/?file=window/window_position_percent.html'
            }, {
                text: '侧边窗体（从下方滑入窗体）',
                href: './mobile/?file=window/window_position_slideup.html'
            }, {
                text: '侧边窗体（动作面板）',
                href: './mobile/?file=window/window_position_actionsheet.html'
            }, {
                text: '侧边窗体（动作面板，按钮分组）',
                href: './mobile/?file=window/window_position_actionsheet_buttongroup.html'
            }, {
                text: '侧边窗体（动作面板，垂直按钮分组）',
                href: './mobile/?file=window/window_position_actionsheet_buttongroup_vertical.html'
            }, {
                text: '侧边窗体（选择日期）',
                href: './mobile/?file=window/window_position_calendar.html'
            }, {
                text: '侧边窗体（选择省市县）',
                href: './mobile/?file=window/window_position_shengshixian.html'
            }]
        }]
    }, {
        text: '选项卡控件',
        children: [{
            text: '选项卡',
            href: './mobile/?file=tabstrip/tabstrip.html'
        }, {
            text: '选项卡（填充）',
            href: './mobile/?file=tabstrip/tabstrip_fill.html'
        }, {
            text: '选项卡（填充，无间距）',
            href: './mobile/?file=tabstrip/tabstrip_fill_space.html'
        }, {
            text: '选项卡（切换动画类型）',
            href: './mobile/?file=tabstrip/tabstrip_animation.html'
        }, {
            text: '选项卡与按钮',
            children: [{
                text: '选项卡（按钮）',
                href: './mobile/?file=tabstrip/tabstrip_button.html'
            }, {
                text: '选项卡（按钮，图标）',
                href: './mobile/?file=tabstrip/tabstrip_button_icon.html'
            }, {
                text: '选项卡（按钮，图标，HBox布局）',
                href: './mobile/?file=tabstrip/tabstrip_button_icon_hbox.html'
            }, {
                text: '选项卡（按钮，图标，HBox布局，图标在上面）',
                href: './mobile/?file=tabstrip/tabstrip_button_icontop_hbox.html'
            }]
        }, {
            text: '选项卡与按钮分组',
            children: [{
                text: '选项卡（按钮分组）',
                href: './mobile/?file=tabstrip/tabstrip_buttongroup.html'
            }, {
                text: '选项卡（按钮分组，图标）',
                href: './mobile/?file=tabstrip/tabstrip_buttongroup_icon.html'
            }, {
                text: '选项卡（按钮分组，图标，HBox布局）',
                href: './mobile/?file=tabstrip/tabstrip_buttongroup_icon_hbox.html'
            }, {
                text: '选项卡（按钮分组，图标，HBox布局，简单按钮样式）',
                href: './mobile/?file=tabstrip/tabstrip_buttongroup_icon_hbox_buttonplain.html'
            }, {
                text: '选项卡（按钮分组，图标，HBox布局，图标在上面）',
                href: './mobile/?file=tabstrip/tabstrip_buttongroup_icontop_hbox.html'
            }, {
                text: '选项卡（按钮分组，图标，HBox布局，图标在上面，简单按钮样式）',
                href: './mobile/?file=tabstrip/tabstrip_buttongroup_icontop_hbox_buttonplain.html'
            }]
        }]
    }, {
        text: '消息框',
        children: [{
            text: '提示对话框',
            href: './mobile/?file=message/alert.html'
        }, {
            text: '确认对话框',
            href: './mobile/?file=message/confirm.html'
        }, {
            text: '输入对话框',
            href: './mobile/?file=message/prompt.html'
        }, {
            text: '通知对话框',
            href: './mobile/?file=message/notify.html'
        }]
    }, {
        text: '动画效果',
        children: [{
            text: '滑动',
            href: './mobile/?file=animation/slide.html'
        }, {
            text: '滑动（四个方向）',
            href: './mobile/?file=animation/slide_position.html'
        }, {
            text: '淡出',
            href: './mobile/?file=animation/fade.html'
        }, {
            text: '弹出',
            href: './mobile/?file=animation/pop.html'
        }, {
            text: '翻转',
            href: './mobile/?file=animation/flip.html'
        }]
    }]
}, {
    text: '页面布局',
    icon: './res/icon/layout_content.png',
    children: [{
        text: '自适应布局（fit）',
        href: './layout/fit.html'
    }, {
        text: '锚点布局（anchor）',
        href: './layout/anchor.html'
    }, {
        text: '列布局（column）',
        href: './layout/column.html'
    }, {
        text: '列布局（column，纵向滚动条）',
        href: './layout/column_scrollbar.html'
    }, {
        text: '列布局（column，自动高度）',
        href: './layout/column_autoheight.html'
    }, {
        text: '表格布局（table）',
        href: './layout/table.html'
    }, {
        text: '绝对定位布局（absolute）',
        href: './layout/absolute.html'
    }, {
        text: '水平盒子布局（hbox）',
        href: './layout/hbox.html'
    }, {
        text: '水平盒子布局（hbox，横向滚动条）',
        href: './layout/hbox_scrollbar.html'
    }, {
        text: '水平盒子布局（hbox，自动高度）',
        href: './layout/hbox_autoheight.html'
    }, {
        text: '水平盒子布局（hbox，自动高度，多层嵌套）',
        href: './layout/hbox_autoheight_multilevels.html'
    }, {
        text: '水平盒子布局（hbox，横向表单）',
        href: './layout/hbox_form.html'
    }, {
        text: '垂直盒子布局（vbox）',
        href: './layout/vbox.html'
    }, {
        text: '垂直盒子布局（vbox，纵向滚动条）',
        href: './layout/vbox_scrollbar.html'
    }, {
        text: '垂直盒子布局（vbox，自动高度）',
        href: './layout/vbox_autoheight.html'
    }, {
        text: '垂直盒子布局（vbox，表单）',
        href: './layout/vbox_form.html'
    }, {
        text: '垂直盒子布局（vbox，表单与表格，纵向滚动条）',
        href: './layout/vbox_formgrid.html'
    }, {
        text: '垂直盒子布局（vbox，折叠面板）',
        href: './layout/vbox_collapse.html'
    }, {
        text: '区域布局（region）',
        href: './layout/region.html'
    }, {
        text: '区域布局（region，自定义分隔条宽度）',
        href: './layout/region_splitwidth.html'
    }, {
        text: '区域布局（region，多个左侧区域）',
        href: './layout/region_multileft.html'
    }, {
        text: '区域布局（region，多个侧边区域）',
        href: './layout/region_multiregions.html'
    }, {
        text: '区域布局（inline-block）',
        href: './layout/inlineblock.html'
    }, {
        text: '区域布局（未定义布局）',
        href: './layout/nolayout.html'
    }]
}, {
    text: '内联框架',
    icon: './res/icon/application_double.png',
    children: [{
        text: '弹出窗体（本页面或父页面）',
        href: './iframe/button_iframe.html'
    }, {
        text: '表格与编辑窗体',
        href: './iframe/grid_iframe.html'
    }, {
        text: '子窗口向父窗口传值',
        href: './iframe/passvalue_iframe.html'
    }, {
        text: '子窗口中选择省份',
        href: './iframe/selectprovince.html'
    }, {
        text: '窗体中的窗体',
        href: './iframe/iframe_iframe.html'
    }, {
        text: '窗体关闭前的确认对话框',
        href: './iframe/window.html'
    }, {
        text: '面板高度随IFrame的高度变化',
        href: './iframe/iframe_autoheight.html'
    }]
}, {
    text: '其他杂项',
    icon: './res/icon/asterisk_orange.png',
    children: [{
        text: '第三方组件',
        children: [{
            text: 'My97日期控件',
            children: [{
                text: 'My97日期控件',
                href: './third-party/my97/my97.html'
            }]
        }, {
            text: 'jQueryUI Autocomplete',
            children: [{
                text: '内联数据',
                href: './third-party/autocomplete/inline.html'
            }, {
                text: '内联数据（位于Window控件中）',
                href: './third-party/autocomplete/inline_window.html'
            }, {
                text: '自动补全邮件地址',
                href: './third-party/autocomplete/email.html'
            }, {
                text: '多行显示补全数据',
                href: './third-party/autocomplete/custom_display.html'
            }, {
                text: '输入逗号分隔的多个值',
                href: './third-party/autocomplete/multi_values.html'
            }]
        }, {
            text: 'UMEditor',
            children: [{
                text: 'UMEditor',
                href: './third-party/umeditor/umeditor.html'
            }, {
                text: 'UMEditor（两个编辑器）',
                href: './third-party/umeditor/umeditor_two.html'
            }, {
                text: 'UMEditor（选项卡与编辑器）',
                href: './third-party/umeditor/umeditor_tabstrip.html'
            }, {
                text: 'UMEditor（自定义配置项）',
                href: './third-party/umeditor/umeditor_config.html'
            }]
        }, {
            text: 'UEditor',
            children: [{
                text: 'UEditor',
                href: './third-party/ueditor/ueditor.html'
            }, {
                text: 'UEditor（两个编辑器）',
                href: './third-party/ueditor/ueditor_two.html'
            }, {
                text: 'UEditor（选项卡与编辑器）',
                href: './third-party/ueditor/ueditor_tabstrip.html'
            }, {
                text: 'UEditor（自定义配置项）',
                href: './third-party/ueditor/ueditor_config.html'
            }]
        }, {
            text: 'CKEditor',
            children: [{
                text: 'CKEditor',
                href: './third-party/ckeditor/ckeditor.html'
            }, {
                text: 'CKEditor（两个编辑器）',
                href: './third-party/ckeditor/ckeditor_two.html'
            }, {
                text: 'CKEditor（选项卡与编辑器）',
                href: './third-party/ckeditor/ckeditor_tabstrip.html'
            }, {
                text: 'CKEditor（自定义配置项）',
                href: './third-party/ckeditor/ckeditor_config.html'
            }]
        }, {
            text: 'TinyMCE',
            children: [{
                text: 'TinyMCE',
                href: './third-party/tinymce/tinymce.html'
            }, {
                text: 'TinyMCE（两个编辑器）',
                href: './third-party/tinymce/tinymce_two.html'
            }, {
                text: 'TinyMCE（选项卡与编辑器）',
                href: './third-party/tinymce/tinymce_tabstrip.html'
            }, {
                text: 'TinyMCE（自定义配置项）',
                href: './third-party/tinymce/tinymce_config.html'
            }]
        }, {
            text: 'ColorPicker',
            children: [{
                text: 'ColorPicker',
                href: './third-party/colorpicker/colorpicker.html'
            }]
        }]
    }, {
        text: '消息框',
        children: [{
            text: '消息框',
            href: './message/message.html'
        }, {
            text: '提示对话框',
            href: './message/alert.html'
        }, {
            text: '输入对话框',
            href: './message/prompt.html'
        }, {
            text: '通知对话框',
            href: './message/notify.html'
        }, {
            text: '通知对话框（向父页面添加选项卡）',
            href: './message/notify_addtab.html'
        }, {
            text: '确认对话框',
            href: './message/confirm_cancel.html'
        }, {
            text: '确认对话框（自定义按钮文本）',
            href: './message/confirm_buttons.html'
        }, {
            text: '确认对话框（自动获取焦点的按钮）',
            href: './message/confirm_buttons_autofocus.html'
        }]
    }, {
        text: '文本框改变事件',
        href: './other/textbox_change.html'
    }, {
        text: '更改文本样式',
        href: './other/cssstyle.html'
    }, {
        text: '表单字段的Label样式',
        href: './other/field_label_style.html'
    }, {
        text: '向父页面添加选项卡',
        href: './other/addtab.html'
    }, {
        text: '捕获全局JavaScript错误',
        href: './other/global_error.html'
    }]
}];